title: Kayla Webb
description: Software Engineer @ Clearbit
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://webbkyr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme-color: indigo
author: Kayla R. Webb
author-bio: Software Engineer @ Clearbit
author-image: IMG_8141.jpg
home-page-quote: To overcome our greatest fears, we have to confront them, like a child lifting the covers, grabbing a flashlight, and peering under the bed to make sure that the boogieman isn’t there after all. Or maybe he is. But at least now you can see him fully. Knowing what you are up against, you can brace yourself, then gather the energy for the fight. — Bozoma Saint John
home-page-quote-source: https://www.penguinrandomhouse.com/books/688798/the-urgent-life-by-bozoma-saint-john/

show-nav-menu: true
nav-menu:
  - text: About
    permalink: about
  - text: Projects
    permalink: projects
  - text: Blog
    permalink: blog
  - text: Reading List
    permalink: books

twitter: false
facebook: false
instagram: false
github: https://github.com/webbkyr
linkedin: https://www.linkedin.com/in/kaylarwebb
medium: false
email: kayla@hey.com
footer-msg: Lanita Technology Solutions

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
